### ISSUE TITLE
Unable to move ShowMeBuffs

### ISSUE THREAD

**Issue by batista315** [Macumbafeh/EasyFrames_wotlk#3]
It's stuck on the far side of my screen, and I can't move it. Not sure what to do

**Comment by Macumbafeh** [comment]
Hello, can you send a screen please.
Make sure to disable all other addons except EasyFrame and ShowMeBuffs to make sure it's not an other addon which is conflicting with it

**Comment by batista315** [comment]
<img width="500" height="205" alt="Image" src="https://github.com/user-attachments/assets/4db18258-32b3-4350-b27d-10f246d0e2e5" />
<img width="529" height="217" alt="Image" src="https://github.com/user-attachments/assets/54aa388e-36e9-4abc-a983-04c9177011d1" />
<img width="552" height="203" alt="Image" src="https://github.com/user-attachments/assets/5c956a49-9f69-4d51-9417-0dc67f0b39b6" />

**Comment by batista315** [comment]
It moves in tandem with moving my unit frame and it is far to the left there. It will even go off screen. The party and target buff works well though.

This is with only EasyFrames, ShowMeBuff, MoveAnything, and AddonControlPanel enabled

**Comment by batista315** [comment]
Another unrelated issue occurred when testing things out. Putting the name inside the frame for both player and targets creates an issue where after reloading/relogging the health text Y axis goes lower and kinda clips into the mana text. It works when you enable it at first, but that's temporary.

I made a really quick mockup of an alternative name bar as well, with a bar behind the name area that is a bit flush with the current frame design. I don't know how I feel about the opacity, but maybe the opacity can be changed. I already had class color enabled, but maybe the class color could go right where this name bar is as well, that way we can use the default health and have it change color from green to red depending on health status. Just an idea

<img width="288" height="114" alt="Image" src="https://github.com/user-attachments/assets/9a3fec2d-23fa-4ebd-96b7-b6055271c44c" />
<img width="325" height="131" alt="Image" src="https://github.com/user-attachments/assets/912b8025-19f5-475a-8fc5-35b665e3b93f" />

**Comment by Macumbafeh** [comment]
I fixed the buff/debuff on PlayerFrame.
I'll check the second issue later.

Fyi i deleted ShowMeBuffs addon from EasyFrame repo because i added an option in the default ShowMeBuffs addon to move the buffs/debuffs lower to match EasyFrames party frames.
You can find it here : https://github.com/wotlk-addons/ShowMeBuff

**Comment by Macumbafeh** [comment]
> Another unrelated issue occurred when testing things out. Putting the name inside the frame for both player and targets creates an issue where after reloading/relogging the health text Y axis goes lower and kinda clips into the mana text. It works when you enable it at first, but that's temporary.
> 
> I made a really quick mockup of an alternative name bar as well, with a bar behind the name area that is a bit flush with the current frame design. I don't know how I feel about the opacity, but maybe the opacity can be changed. I already had class color enabled, but maybe the class color could go right where this name bar is as well, that way we can use the default health and have it change color from green to red depending on health status. Just an idea
> 
> <img alt="Image" width="288" height="114" src="https://private-user-images.githubusercontent.com/126232439/481923345-9a3fec2d-23fa-4ebd-96b7-b6055271c44c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyMjQzNTksIm5iZiI6MTc1NjIyNDA1OSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgxOTIzMzQ1LTlhM2ZlYzJkLTIzZmEtNGViZC05NmI3LWI2MDU1MjcxYzQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQxNjAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzkwNDUxMDA1NThmY2YyY2JlNzM3YjJjYWIyYmEyMmRhNzY1MzIyZjYxYjEyMDdiMWM3Njc1YTliMWE2YmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DF58xj4j3obdvwRPpzXFPcOtfPwozxuUsX6hSI7hBHM"> <img alt="Image" width="325" height="131" src="https://private-user-images.githubusercontent.com/126232439/481923344-912b8025-19f5-475a-8fc5-35b665e3b93f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyMjQzNTksIm5iZiI6MTc1NjIyNDA1OSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgxOTIzMzQ0LTkxMmI4MDI1LTE5ZjUtNDc1YS04ZmM1LTM1YjY2NWUzYjkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQxNjAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjQ5YjcyZjNmNDBlYjRhM2YxZWI0MjMxYWJmODllODY4YzRiZDU5NTRmNDJkODZhODQ4NzI3ZWJhYTBiM2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZzXB4xZanGpxyyyQqZAMYpmA3N3_Fthl-1S3em05sSY">

I fixed it on player, target, focus and Boss frame.

After a relog

<img width="1249" height="695" alt="Image" src="https://github.com/user-attachments/assets/438367a3-b9b5-40fb-91cb-6566b518c332" />

**Comment by Macumbafeh** [comment]
download it again and tell me how it is.

**Comment by batista315** [comment]
It works. Sorta. I'll be using the name inside the frame now, but for future reference this kinda does the inverse and makes the default name over the frame have the health text really high up on the Y. Just might be an issue for anyone that prefers using that one instead

<img width="288" height="123" alt="Image" src="https://github.com/user-attachments/assets/f0bbc9bd-024b-48ff-abde-9fa6a76cf848" />

**Comment by batista315** [comment]
> I fixed the buff/debuff on PlayerFrame. I'll check the second issue later.
> 
> Fyi i deleted ShowMeBuffs addon from EasyFrame repo because i added an option in the default ShowMeBuffs addon to move the buffs/debuffs lower to match EasyFrames party frames. You can find it here : https://github.com/wotlk-addons/ShowMeBuff

Ok downloaded both, and for some reason now I can't see any of my buffs at all with SMB. Not even in some far off corner. Did a reset and it still wont show up anywhere

**Comment by Macumbafeh** [comment]
> It works. Sorta. I'll be using the name inside the frame now, but for future reference this kinda does the inverse and makes the default name over the frame have the health text really high up on the Y. Just might be an issue for anyone that prefers using that one instead
> 
> <img alt="Image" width="288" height="123" src="https://private-user-images.githubusercontent.com/126232439/482294685-f0bbc9bd-024b-48ff-abde-9fa6a76cf848.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDA1MzAsIm5iZiI6MTc1NjI0MDIzMCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyMjk0Njg1LWYwYmJjOWJkLTAyNGItNDhmZi1hYmRlLTlmYTZhNzZjZjg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQyMDMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzY1NWZhZDI2NjUwNDJkMjM4YTkxZDVlNDQ3NjZiNmUyZDdlMzE1MDQ0NzcxYmFhZWFmMGNjYmQ1OGI3Yjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gu4dALfD65bosnuYnxtFe4JG6kMYt30D24gVjGZavLg">

Nice catch i'll try when it's disabled

**Comment by Macumbafeh** [comment]
> > I fixed the buff/debuff on PlayerFrame. I'll check the second issue later.
> > Fyi i deleted ShowMeBuffs addon from EasyFrame repo because i added an option in the default ShowMeBuffs addon to move the buffs/debuffs lower to match EasyFrames party frames. You can find it here : https://github.com/wotlk-addons/ShowMeBuff
> 
> Ok downloaded both, and for some reason now I can't see any of my buffs at all with SMB. Not even in some far off corner. Did a reset and it still wont show up anywhere

I deleted it from the player frame, i thought you didn't want it.
For SMB take this version for the moment to get the option to move buff on party frames
https://github.com/Macumbafeh/ShowMeBuff

**Comment by batista315** [comment]
> > > I fixed the buff/debuff on PlayerFrame. I'll check the second issue later.
> > > Fyi i deleted ShowMeBuffs addon from EasyFrame repo because i added an option in the default ShowMeBuffs addon to move the buffs/debuffs lower to match EasyFrames party frames. You can find it here : https://github.com/wotlk-addons/ShowMeBuff
> > 
> > 
> > Ok downloaded both, and for some reason now I can't see any of my buffs at all with SMB. Not even in some far off corner. Did a reset and it still wont show up anywhere
> 
> I deleted it from the player frame, i thought you didn't want it. For SMB take this version for the moment to get the option to move buff on party frames https://github.com/Macumbafeh/ShowMeBuff

No I really liked seeing the buffs I had. I just wanted them to be in a better position, or even moveable

**Comment by Macumbafeh** [comment]
> It works. Sorta. I'll be using the name inside the frame now, but for future reference this kinda does the inverse and makes the default name over the frame have the health text really high up on the Y. Just might be an issue for anyone that prefers using that one instead
> 
> <img alt="Image" width="288" height="123" src="https://private-user-images.githubusercontent.com/126232439/482294685-f0bbc9bd-024b-48ff-abde-9fa6a76cf848.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDI2MDcsIm5iZiI6MTc1NjI0MjMwNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyMjk0Njg1LWYwYmJjOWJkLTAyNGItNDhmZi1hYmRlLTlmYTZhNzZjZjg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQyMTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGRlMmZkZjQyNTIzOWU2MTNhZDM0YmQ5OGZmN2RlY2E0ZWE0Y2Q5OGMwMjBiYzcwOTg4YzIwZjYyMWU5YzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._GfZTyGTTs0F7OthtVDWGAwtsLX7Z4LZQP0UiGGgNaM">

fixed.

i'll bring back the player buff then and position it below the player frame

**Comment by batista315** [comment]
> > It works. Sorta. I'll be using the name inside the frame now, but for future reference this kinda does the inverse and makes the default name over the frame have the health text really high up on the Y. Just might be an issue for anyone that prefers using that one instead
> > <img alt="Image" width="288" height="123" src="https://private-user-images.githubusercontent.com/126232439/482294685-f0bbc9bd-024b-48ff-abde-9fa6a76cf848.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDI2MDcsIm5iZiI6MTc1NjI0MjMwNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyMjk0Njg1LWYwYmJjOWJkLTAyNGItNDhmZi1hYmRlLTlmYTZhNzZjZjg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQyMTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGRlMmZkZjQyNTIzOWU2MTNhZDM0YmQ5OGZmN2RlY2E0ZWE0Y2Q5OGMwMjBiYzcwOTg4YzIwZjYyMWU5YzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._GfZTyGTTs0F7OthtVDWGAwtsLX7Z4LZQP0UiGGgNaM">
> 
> fixed.
> 
> i'll bring back the player buff then and position it below the player frame

I like having mine on top :), Idk if this is asking for too much. Maybe a tick for on top or below. Also, I make my unit frames for the party a bit bigger and I think this causes the buff frame for SMB to clip under the frame. Like this

<img width="497" height="741" alt="Image" src="https://github.com/user-attachments/assets/602f54db-4367-49be-8783-8107fb916460" />

**Comment by Macumbafeh** [comment]
> > > It works. Sorta. I'll be using the name inside the frame now, but for future reference this kinda does the inverse and makes the default name over the frame have the health text really high up on the Y. Just might be an issue for anyone that prefers using that one instead
> > > <img alt="Image" width="288" height="123" src="https://private-user-images.githubusercontent.com/126232439/482294685-f0bbc9bd-024b-48ff-abde-9fa6a76cf848.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDI2MDcsIm5iZiI6MTc1NjI0MjMwNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyMjk0Njg1LWYwYmJjOWJkLTAyNGItNDhmZi1hYmRlLTlmYTZhNzZjZjg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQyMTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGRlMmZkZjQyNTIzOWU2MTNhZDM0YmQ5OGZmN2RlY2E0ZWE0Y2Q5OGMwMjBiYzcwOTg4YzIwZjYyMWU5YzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._GfZTyGTTs0F7OthtVDWGAwtsLX7Z4LZQP0UiGGgNaM">
> > 
> > 
> > fixed.
> > i'll bring back the player buff then and position it below the player frame
> 
> I like having mine on top :), Idk if this is asking for too much. Maybe a tick for on top or below. Also, I make my unit frames for the party a bit bigger and I think this causes the buff frame for SMB to clip under the frame. Like this
> 
> <img alt="Image" width="497" height="741" src="https://private-user-images.githubusercontent.com/126232439/482358236-602f54db-4367-49be-8783-8107fb916460.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDU2NDUsIm5iZiI6MTc1NjI0NTM0NSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyMzU4MjM2LTYwMmY1NGRiLTQzNjctNDliZS04NzgzLTgxMDdmYjkxNjQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQyMTU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzJmY2U2MjllMWFjOTliYjE4ZjhmMjJmNzI1MjRmYTk4ZjY1YjVhN2E4NjRhYmY3MDFiYjQ3OWExOGIxZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3_KMVjEnVmL_O-w3Yrff4ijiLUVKXlkCoGLsAfKJjaU">

for the moment it's like this, and i set my Party Frames to 2 (very big) and it well placed

<img width="1601" height="705" alt="Image" src="https://github.com/user-attachments/assets/b7c7dbb6-e414-4dbf-ace7-209aad535889" />

You just need to take the SMB from my github and enable this option

<img width="803" height="611" alt="Image" src="https://github.com/user-attachments/assets/d73eaba6-a04f-4a3e-a7d8-c997fe9be031" />

**Comment by Macumbafeh** [comment]
i have set an option to have it like i showed you or like this

<img width="657" height="451" alt="Image" src="https://github.com/user-attachments/assets/20935693-7d96-4a67-a4b2-a3dad5b08163" />

Tell me if it's like you want or send a screen to show me how it should be

The option

<img width="871" height="607" alt="Image" src="https://github.com/user-attachments/assets/651568d6-d5a9-4e00-88aa-b5c0655478dd" />

Here btw : https://github.com/Macumbafeh/ShowMeBuff

**Comment by batista315** [comment]
Think this is as good as it can get. I owe you big time! You got one of those coffee link whatevers?

**Comment by batista315** [comment]
Wait, I did notice a couple things, as well as some implementations that I think would be neat as well. 

1. When displaying the buffs on top, can you invert the line order? Instead of going downwards and clipping into the unitframe, maybe have it grow inverse/upwards instead? 
<img width="280" height="126" alt="Image" src="https://github.com/user-attachments/assets/2b45dfc5-84e1-4021-b6f1-0c8d1307aecc" />

2. Is there any way to make a max amount of lines? Think anything past 2 I a little too much. If this isn't possible, no problem!
 
3. Also, for "name in health bar" people, it would be nicer to have less of a gap between the frame and buffs. Here <img width="235" height="143" alt="Image" src="https://github.com/user-attachments/assets/e91fbf40-9c45-4000-b3e2-fc1188c7c984" />
 
4. I think maybe shifting the buffs slightly to the left so that it can fit 6 would be great too. Using buff size 20 since that one is the smallest it can show you timers for the buffs.
<img width="358" height="161" alt="Image" src="https://github.com/user-attachments/assets/a4f4244f-672c-45dd-8905-30f2cdbb8bb4" />

5. The ability to turn off hiding the "longer than X minutes" or increasing the amount of minutes to maybe 3 hours could be nice too. My weapon buff lasts an hour, and even though some time has passed and it is no longer an hour, it still won't show up on my frame.
<img width="74" height="80" alt="Image" src="https://github.com/user-attachments/assets/19870733-35b6-4d56-a61f-d3401b06cbbc" />
<img width="245" height="66" alt="Image" src="https://github.com/user-attachments/assets/c0a2b942-8300-4065-8313-226d98eb841f" />

6. Not sure if this is an EasyFrames or SMB issue, but target frame buffs make a new line at 5, even if I have it set for a higher number. 

7. I made a better mockup based off the one I posted earlier using target frame since I was able to edit that easier with MoveAny, but ideally would apply to all frames, even party and boss. I put 7 frames on the line, but 6 works too
<img width="284" height="154" alt="Image" src="https://github.com/user-attachments/assets/ffeac3ae-1d08-480f-b07e-190a97489e83" />

**Comment by Macumbafeh** [comment]
> Think this is as good as it can get. I owe you big time! You got one of those coffee link whatevers?

I have a paypal if you want to show love ❤️ 
https://www.paypal.me/macumbafeh

**Comment by Macumbafeh** [comment]
> Wait, I did notice a couple things, as well as some implementations that I think would be neat as well.
> 
> 1. When displaying the buffs on top, can you invert the line order? Instead of going downwards and clipping into the unitframe, maybe have it grow inverse/upwards instead?
> 
> <img alt="Image" width="280" height="126" src="https://private-user-images.githubusercontent.com/126232439/482448913-2b45dfc5-84e1-4021-b6f1-0c8d1307aecc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ4OTEzLTJiNDVkZmM1LTg0ZTEtNDAyMS1iNmYxLTBjOGQxMzA3YWVjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTU3ODA3Mjg4MDU0NDk5YjNhNDQzNDE4ZTliNTI4ZjMxZTkxNjczNDc5ZjNkYmFjMTliYmZkNDhkZmE2MWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GDbFY3ZYiCZqNGuoC6zU80Bu7uHn2G_daNamLjotVOw">
> 2. Is there any way to make a max amount of lines? Think anything past 2 I a little too much. If this isn't possible, no problem!
> 3. Also, for "name in health bar" people, it would be nicer to have less of a gap between the frame and buffs. Here <img alt="Image" width="235" height="143" src="https://private-user-images.githubusercontent.com/126232439/482446984-e91fbf40-9c45-4000-b3e2-fc1188c7c984.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ2OTg0LWU5MWZiZjQwLTljNDUtNDAwMC1iM2UyLWZjMTE4OGM3Yzk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGE3OTAwMjEwNGVmMjc0ZmVjMmY2MDM0Y2U3YmZkZDdhNWIzODk4M2M3MjQwODBiMjhjYjVhNGY5ZjEzMDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3hJHTDBsrroq6tXOab9_LhNwK2wVKaR9yPPQJprInUY">
> 4. I think maybe shifting the buffs slightly to the left so that it can fit 6 would be great too. Using buff size 20 since that one is the smallest it can show you timers for the buffs.
> 
> <img alt="Image" width="358" height="161" src="https://private-user-images.githubusercontent.com/126232439/482448493-a4f4244f-672c-45dd-8905-30f2cdbb8bb4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ4NDkzLWE0ZjQyNDRmLTY3MmMtNDVkZC04OTA1LTMwZjJjZGJiOGJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDAwYmE3NWQ2MThiODJhOTE4ZjMwMjRjYWIzZDliNTU0OGZiMzA2ZWRkZTQwZTMxOGNiM2MwYjU5YThlYTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9uxtl7Ev0aSwefjtHaLujNnBrnLnLbzKsItyGNJBni8">
> 5. The ability to turn off hiding the "longer than X minutes" or increasing the amount of minutes to maybe 3 hours could be nice too. My weapon buff lasts an hour, and even though some time has passed and it is no longer an hour, it still won't show up on my frame.
> 
> <img alt="Image" width="74" height="80" src="https://private-user-images.githubusercontent.com/126232439/482449760-19870733-35b6-4d56-a61f-d3401b06cbbc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ5NzYwLTE5ODcwNzMzLTM1YjYtNGQ1Ni1hNjFmLWQzNDAxYjA2Y2JiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzNhMzE3MzFhNTk2OGRhNmYzZTY0Y2QzZmY2NTljYjdmNTc0MWIxOTQ5NjgyYjFkYzIxMjAyMDM5MTQzYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GDoG9fWPdT-QPPr1Osv7BWJeMTmSea_fFoY57VKGFxk"> <img alt="Image" width="245" height="66" src="https://private-user-images.githubusercontent.com/126232439/482449761-c0a2b942-8300-4065-8313-226d98eb841f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ5NzYxLWMwYTJiOTQyLTgzMDAtNDA2NS04MzEzLTIyNmQ5OGViODQxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTIzZGEyOTAxNjUyMzYyYzQ0ZDY5OTNjMGI1OTllYjcxYjg2MWM2MjIwNTg2ZDBmZDRhYjRiN2UxMDM0NjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fgvANogCx_F4M-ZfGI85Cx-2WmDfylzIgnMl3a0LeZ4">
> 6. Not sure if this is an EasyFrames or SMB issue, but target frame buffs make a new line at 5, even if I have it set for a higher number.
> 7. I made a better mockup based off the one I posted earlier using target frame since I was able to edit that easier with MoveAny, but ideally would apply to all frames, even party and boss. I put 7 frames on the line, but 6 works too
> 
> <img alt="Image" width="284" height="154" src="https://private-user-images.githubusercontent.com/126232439/482463214-ffeac3ae-1d08-480f-b07e-190a97489e83.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNzkzODgsIm5iZiI6MTc1NjI3OTA4OCwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDYzMjE0LWZmZWFjM2FlLTFkMDgtNDgwZi1iMDdlLTE5MGE5NzQ4OWU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QwNzE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjYyNjYxYjY0N2RmMzdkMTliMDM5NWFlNjQwZmJlY2ZlOGNlMzAwN2ExYWNmMzBkZmZiNjhkNTFmZTA5ODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HScIObaQHmLy3BfrEFC6ozaiGKp_X-IZm4yFvO1yj6E">

For the name inside the frame and buff position, i had it in mind, i'll check for other things.

**Comment by batista315** [comment]
Unrelated, but there's a new Discord for Project Epoch addons, and it would be nice for you to join. You'd get your own channel as a developer where you can post more updates about EF, SMB, and any new addons you might work on in the future.

[Here's a link if you wanna join.](https://github.com/Macumbafeh/EasyFrames_wotlk/)

**Comment by batista315** [comment]
One last thing I wanted to bring up about SMB. Is there a way to enable the tooltip to see more information about a buff like the way the target frame buffs operate?

<img width="430" height="173" alt="Image" src="https://github.com/user-attachments/assets/c0546573-d615-47b0-89b8-04f2a45c7a16" />

**Comment by Macumbafeh** [comment]
Work in 

> Wait, I did notice a couple things, as well as some implementations that I think would be neat as well.
> 
> 1. When displaying the buffs on top, can you invert the line order? Instead of going downwards and clipping into the unitframe, maybe have it grow inverse/upwards instead?
> 
> <img alt="Image" width="280" height="126" src="https://private-user-images.githubusercontent.com/126232439/482448913-2b45dfc5-84e1-4021-b6f1-0c8d1307aecc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ4OTEzLTJiNDVkZmM1LTg0ZTEtNDAyMS1iNmYxLTBjOGQxMzA3YWVjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmQ5N2ZkNGRmZjE0NThhMjc1ZDA4YjAwYjg2MDM3NWZkMjhiZjFmYmFhNGUwYzQ1ZDM4MjRkNDE5OGVhYmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zbGlHM2tm_bbQI_FhfiQ6SxOnMaDtcbpy-lMbFvJz5Q">
> 2. Is there any way to make a max amount of lines? Think anything past 2 I a little too much. If this isn't possible, no problem!
> 3. Also, for "name in health bar" people, it would be nicer to have less of a gap between the frame and buffs. Here <img alt="Image" width="235" height="143" src="https://private-user-images.githubusercontent.com/126232439/482446984-e91fbf40-9c45-4000-b3e2-fc1188c7c984.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ2OTg0LWU5MWZiZjQwLTljNDUtNDAwMC1iM2UyLWZjMTE4OGM3Yzk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODJjZWI3NzVlZmY5MGQ0NmE0YjM3MGExZDY1MmNiZTE0MmE2OGM3YThiNjkxY2FkNDIyZWIwNGVjNjllMGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hj4FBQfJZ8NbSMyxyDZflsBKP64HWhulnzb0gJZGcY0">
> 4. I think maybe shifting the buffs slightly to the left so that it can fit 6 would be great too. Using buff size 20 since that one is the smallest it can show you timers for the buffs.
> 
> <img alt="Image" width="358" height="161" src="https://private-user-images.githubusercontent.com/126232439/482448493-a4f4244f-672c-45dd-8905-30f2cdbb8bb4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ4NDkzLWE0ZjQyNDRmLTY3MmMtNDVkZC04OTA1LTMwZjJjZGJiOGJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTk1ZTQwZjBmMGIxZDNlNDQ5YjNhNzIzZGVhZGU4MDI0ZDRhNjg2YTA1NDBkYWRkNGI2NmUxNmY1NzBmNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XYCvdCH9FuAuggcZTjWgZfK3GMI--SafI8SNhmccaRE">
> 5. The ability to turn off hiding the "longer than X minutes" or increasing the amount of minutes to maybe 3 hours could be nice too. My weapon buff lasts an hour, and even though some time has passed and it is no longer an hour, it still won't show up on my frame.
> 
> <img alt="Image" width="74" height="80" src="https://private-user-images.githubusercontent.com/126232439/482449760-19870733-35b6-4d56-a61f-d3401b06cbbc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ5NzYwLTE5ODcwNzMzLTM1YjYtNGQ1Ni1hNjFmLWQzNDAxYjA2Y2JiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWRhMWQyYzBkMDRjMjcyOGY0MmVkNmJmZjJmMWIxOWJjNzJhMmFkNjAxY2Y2NzQ5YWI5MzFmYzBjMjc1NWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5pdogwMjzAYtcHEfY12UXQuhMynjt5EQ9bMbzHoBGvo"> <img alt="Image" width="245" height="66" src="https://private-user-images.githubusercontent.com/126232439/482449761-c0a2b942-8300-4065-8313-226d98eb841f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDQ5NzYxLWMwYTJiOTQyLTgzMDAtNDA2NS04MzEzLTIyNmQ5OGViODQxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmJmM2E5NDI3OTE3MTlhODYzNTdmMmJiM2QwMTEwMGMzZmZhNjRkODQ1M2QxMmVlYjE5ODNjYzU2YjcyYjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TZxGfPaAodatC-NPcgrO96tepAn04DWpjz4VJJFTtns">
> 6. Not sure if this is an EasyFrames or SMB issue, but target frame buffs make a new line at 5, even if I have it set for a higher number.
> 7. I made a better mockup based off the one I posted earlier using target frame since I was able to edit that easier with MoveAny, but ideally would apply to all frames, even party and boss. I put 7 frames on the line, but 6 works too
> 
> <img alt="Image" width="284" height="154" src="https://private-user-images.githubusercontent.com/126232439/482463214-ffeac3ae-1d08-480f-b07e-190a97489e83.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzM0MjcsIm5iZiI6MTc1NjMzMzEyNywicGF0aCI6Ii8xMjYyMzI0MzkvNDgyNDYzMjE0LWZmZWFjM2FlLTFkMDgtNDgwZi1iMDdlLTE5MGE5NzQ4OWU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjk0MzE1M2Q3MDAzMWY3NzhmMDI5ZTM4ODM0MDc4OTA2NzI2ODNkYjYyNzI1YjUwNTExOGJiYmJkYzI1ODBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N1KyTxifvLvBrKbBj9didYLhSlvTM7Yt1dnLfAJN9NQ">

Work in progress

<img width="1875" height="717" alt="Image" src="https://github.com/user-attachments/assets/1a4a82c7-0aa5-4529-beab-ca5622c0bbd0" />

- As you can see i kept the toggle for party buff for EasyFrames
- I added a toggle for buff growing upward
- i added sliders to position buffs and debuffs where you want.
- I changed the timer duration hiding option to 180 instead of 60

on my side lines are ok even if i set higher the 5 it respect it.

<img width="462" height="311" alt="Image" src="https://github.com/user-attachments/assets/f82ea1f3-9fd1-4585-b1aa-a3f3eee53629" />

<img width="389" height="278" alt="Image" src="https://github.com/user-attachments/assets/96d0a135-81a1-4366-836b-b097da74303d" />

so
1. done with the sliders
2. not sure to understand, but i guess it's a nop
3. done with the sliders too
4. same the sliders does the job
5. done
6. couldn't replicate
7. i don't understand, on party it works and i don't get why you talk about boss frame

I'm on the Epoch discord but i don't play on this serv so i don't plan to make any addon for this serv sorry.

**Comment by batista315** [comment]
> so
> 
>     1. done with the sliders
> 
>     2. not sure to understand, but i guess it's a nop
> 
>     3. done with the sliders too
> 
>     4. same the sliders does the job
> 
>     5. done
> 
>     6. couldn't replicate
> 
>     7. i don't understand, on party it works and i don't get why you talk about boss frame
> 
> 
> I'm on the Epoch discord but i don't play on this serv so i don't plan to make any addon for this serv sorry.

This is what I mean for number 2. Stop the amount of buffs from being shown after 2 lines. I guess maybe a way to do this is max buffs? I'm currently away from my desktop, so apologies if this is already a thing

<img width="462" height="311" alt="Image" src="https://github.com/user-attachments/assets/8c6db360-bdcf-4246-9fd9-38ca349dbbed" />

Also? What's that other icon area there that I circled? Is that the debuff frame? Is there a way to make that stack on top/under the buffs so they can all be in the same place?

And I bring up boss frames because it's a setting there in EasyFrames but now that you mention it I don't think that stuff exists for classic right?

Did you see that other message I posted about the tooltip?

> One last thing I wanted to bring up about SMB. Is there a way to enable the tooltip to see more information about a buff like the way the target frame buffs operate?
> <img alt="Image" width="430" height="173" src="https://private-user-images.githubusercontent.com/126232439/482805523-c0546573-d615-47b0-89b8-04f2a45c7a16.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzcyOTksIm5iZiI6MTc1NjMzNjk5OSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyODA1NTIzLWMwNTQ2NTczLWQ2MTUtNDdiMC04OWI4LTA0ZjJhNDVjN2ExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA0MGY4MGVjOTIzYmIyMDM1M2M2ZGRiMzdjZGEwNGU2ZDgwYWI4OGEwZGNlZTU5Yzk4YWU2YjRiYjYxNGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l_0zYQR8aOiCbwi9IAfKLKdgjKMmkRqDHKXnxdv31HQ">


And no problem for the Discord stuff, they're just recruiting and I'm asking anyone who is a developer for 3.3.5 addons if they'd like to join.

**Comment by Macumbafeh** [comment]
> > so
> > ```
> > 1. done with the sliders
> > 
> > 2. not sure to understand, but i guess it's a nop
> > 
> > 3. done with the sliders too
> > 
> > 4. same the sliders does the job
> > 
> > 5. done
> > 
> > 6. couldn't replicate
> > 
> > 7. i don't understand, on party it works and i don't get why you talk about boss frame
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm on the Epoch discord but i don't play on this serv so i don't plan to make any addon for this serv sorry.
> 
> This is what I mean for number 2. Stop the amount of buffs from being shown after 2 lines. I guess maybe a way to do this is max buffs? I'm currently away from my desktop, so apologies if this is already a thing
> 
> <img alt="Image" width="462" height="311" src="https://private-user-images.githubusercontent.com/126232439/482896929-8c6db360-bdcf-4246-9fd9-38ca349dbbed.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzc3NDEsIm5iZiI6MTc1NjMzNzQ0MSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyODk2OTI5LThjNmRiMzYwLWJkY2YtNDI0Ni05ZmQ5LTM4Y2EzNDlkYmJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMzMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWYzZTE0NDY2NWUyZmRjMWNhYzQzNTcxMzAyZTdmNWQ2OGM1ODNhZGE3MjY2M2Y2ZmNhNzM5MjE3YWI5NjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gvl2RazdoX5tRWGC-vy7Y9e0mvW2x5fGQ4aIOl8SFf0">
> Also? What's that other icon area there that I circled? Is that the debuff frame? Is there a way to make that stack on top/under the buffs so they can all be in the same place?
> 
> And I bring up boss frames because it's a setting there in EasyFrames but now that you mention it I don't think that stuff exists for classic right?
> 
> Did you see that other message I posted about the tooltip?
> 
> > One last thing I wanted to bring up about SMB. Is there a way to enable the tooltip to see more information about a buff like the way the target frame buffs operate?
> > <img alt="Image" width="430" height="173" src="https://private-user-images.githubusercontent.com/126232439/482805523-c0546573-d615-47b0-89b8-04f2a45c7a16.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzMzcyOTksIm5iZiI6MTc1NjMzNjk5OSwicGF0aCI6Ii8xMjYyMzI0MzkvNDgyODA1NTIzLWMwNTQ2NTczLWQ2MTUtNDdiMC04OWI4LTA0ZjJhNDVjN2ExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyN1QyMzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA0MGY4MGVjOTIzYmIyMDM1M2M2ZGRiMzdjZGEwNGU2ZDgwYWI4OGEwZGNlZTU5Yzk4YWU2YjRiYjYxNGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l_0zYQR8aOiCbwi9IAfKLKdgjKMmkRqDHKXnxdv31HQ">
> 
> And no problem for the Discord stuff, they're just recruiting and I'm asking anyone who is a developer for 3.3.5 addons if they'd like to join.

The icon you circled is the debuff yeah, you can place it where you want now with the slider option. I just placed it there.

I saw and i tested to add tooltip, i have a version which works but throw tons of errors. For the moment i don't think i'll add it.

**Comment by batista315** [comment]
Got it, ty for the hard work anyway my friend. Can I get your permission to post about this on the Epoch Discord?

**Comment by batista315** [comment]
For party buffs, can we get a separate buff size modifier. I scale my party frames to be larger but it also makes the party buffs larger larger
<img width="307" height="132" alt="Image" src="https://github.com/user-attachments/assets/642e45d3-7906-4223-a4f1-c4c212b4c6f4" />
Similarly, can we get a debuff size modifier as well?

Lastly, some buffs still don't make it through. I can't see weapon buffs still.

<img width="319" height="158" alt="Image" src="https://github.com/user-attachments/assets/da6bbd3b-e0c4-45e6-b3a9-a755ce022c3a" />
<img width="132" height="86" alt="Image" src="https://github.com/user-attachments/assets/37274e1b-692a-4940-b6c6-ebbb5c71aeb3" />

**Comment by Macumbafeh** [comment]
> Got it, ty for the hard work anyway my friend. Can I get your permission to post about this on the Epoch Discord?

it's ok for me.

For the moment i added debuff sizing and added the Weapon Enchant display.

**Comment by Macumbafeh** [comment]
Added sliders to separate buffs/debuffs on party and player's one size.
The enchant weapons isn't perfect. it doesn't show any timer and i don't know how to do yet.
Thanks for the tip <3

**Comment by batista315** [comment]
One thing I've noticed with EasyFrames I keep forgetting about. 

<img width="556" height="213" alt="Image" src="https://github.com/user-attachments/assets/bb608397-69bf-4626-b75f-734df9e6bc49" />

The text for dead status on players and targets over/underlaps with the names. Is this fixable?

**Comment by Macumbafeh** [comment]
> One thing I've noticed with EasyFrames I keep forgetting about.
> 
> <img alt="Image" width="556" height="213" src="https://private-user-images.githubusercontent.com/126232439/488038065-bb608397-69bf-4626-b75f-734df9e6bc49.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc3ODk5ODAsIm5iZiI6MTc1Nzc4OTY4MCwicGF0aCI6Ii8xMjYyMzI0MzkvNDg4MDM4MDY1LWJiNjA4Mzk3LTY5YmYtNDYyNi1iNzVmLTczNGRmOWU2YmM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxM1QxODU0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTQ0NjFmODk1YjQ2NGMwYjc4ZjhmZDlmMTllMDA4NzYzMzVhNTY4ZTI1MDNkNzBiZTRhNmYxYjYwZWY1YTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D3PoY_JEFCV_cJ3U5pYaBTUES30H1wqZ9KpT0_BM9SM">
> The text for dead status on players and targets over/underlaps with the names. Is this fixable?

Same issue than before with health. when you relog/reload it will be not well placed. i'll check when i get time

**Comment by Macumbafeh** [comment]
> One thing I've noticed with EasyFrames I keep forgetting about.
> 
> <img alt="Image" width="556" height="213" src="https://private-user-images.githubusercontent.com/126232439/488038065-bb608397-69bf-4626-b75f-734df9e6bc49.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc5NTYwNTIsIm5iZiI6MTc1Nzk1NTc1MiwicGF0aCI6Ii8xMjYyMzI0MzkvNDg4MDM4MDY1LWJiNjA4Mzk3LTY5YmYtNDYyNi1iNzVmLTczNGRmOWU2YmM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxNVQxNzAyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTA0N2Q2N2FiNTczNDVhYTYwMmZhZDcyNDA0YmFjYmY1NGE1MzgyODgwNjRlZTUwNTQ0MDFlMTM5NzMxZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VOXCzXDUIcNtAaK_-n8o_zx-wK-m453X7Ns94dNaB6I">
> The text for dead status on players and targets over/underlaps with the names. Is this fixable?

Can you reset your wtf saves please? Close the game and go into folders : WTF > account > account_name > SavedVariables and then delete all EasyFrames files.
It will reset the addon, you will lose your saves. but i think it will fix it.
I was trying to get a fix but it wasn't working... i reseted it and now it works without any changes 👍 

It seems the previous fix i did break it too...

**Comment by Macumbafeh** [comment]
It was a bit my fault again. no need to reset, but it's better anyway...
I cleaned the code and now it should be good.
